variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Official docker compose image.
image:
  name: docker/compose

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose -f docker-compose-prod.yml down
    - docker-compose -f docker-compose-prod.yml build
    - docker-compose -f docker-compose-prod.yml up -d

test:
  stage: test
  script:
    - docker-compose -f docker-compose-prod.yml run users ./service init
    - docker-compose -f docker-compose-prod.yml run users ./service test
  after_script:
    - docker-compose -f docker-compose-prod.yml stop
